### ISSUE TITLE
Properties marked with visible=false are still shown in admin

### ISSUE THREAD

**Issue by PerWiklander** [bjorn-ali-goransson/PostTypeBuilder#2]
It looks like the if statement here:
https://github.com/bornemix/PostTypeBuilder/blob/master/admin/post-screen.php#L99

should include the whole table row, so that only the html in the else clause is printed if `visible == false`

**Comment by PerWiklander** [comment]
Time to abandon this, me thinks :-)

**Comment by bjorn-ali-goransson** [comment]
Definetely. Sorry for being so unresponsive.

What do you use instead? I myself use ACF...

**Comment by PerWiklander** [comment]
I haven't touched WP in four years and I sleep much better at night now :-)

**Comment by bjorn-ali-goransson** [comment]
EPiServer? Or still PHP?

**Comment by PerWiklander** [comment]
Well, WP once saved me from EPiServer hell :-) I actually do write PHP code at the moment, but that is not of my own choosing. It's mostly Scala only these days.

**Comment by bjorn-ali-goransson** [comment]
Thats nice... episerver has grown up though 👌

Den 24 maj 2017 16:54 skrev "Per Wiklander" <notifications@github.com>:
